#lang racket

(define (squarer a b)
  (define (process-new-value)
    (if (has-value? b)
        (if (< (get-value b) 0)
            (error "квадрат меньше 0 -- SQUARER" (get-value b))
            (set-value! a (sqrt (get-value b)) me))
        (set-value! b (* (get-value a) (get-value a)) me)))
  (define (process-forget-value)
    (forget-value! a)
    (forget-value! b))
  (define (me request)
    (cond ((eq? request 'I-have-value)
           (process-new-value))
          ((eq? request 'I-lost-me-value)
           (process-forgot-value))
          (else (error "Неизвестный запрос"))))
  (connect a me)
  (connect b me)
  me)